name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install project dependencies
        run: uv sync
      - name: Build static site
        run: uv run --with taskify task build
      - name: Add .nojekyll file
        run: touch docs/.nojekyll
      - name: Add CNAME file
        run: echo 'rendeiro.group' > docs/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
